import { Audio, staticFile, Sequence } from "remotion";
import { chapters, FPS } from "../chapters";

/**
 * Voiceover track.
 *
 * Each chapter has a short narration (~3-6s) that fits inside its 12s window.
 * We use <Sequence> to time-clip each audio file to its chapter's frame range.
 *
 * Files live in public/vo/ — generated by the TTS step before the build.
 */
export const Narration: React.FC = () => {
  return (
    <>
      {/* intro — frames 0 → 6s */}
      <Sequence from={0} durationInFrames={6 * FPS}>
        <Audio src={staticFile("vo/00-intro.mp3")} volume={1} />
      </Sequence>

      {/* per-chapter narration — from chapter start to chapter end */}
      {chapters.map((c) => {
        const dur = c.endFrame - c.startFrame;
        return (
          <Sequence key={c.id} from={c.startFrame} durationInFrames={dur}>
            <Audio src={staticFile(`vo/${c.id}.mp3`)} volume={1} />
          </Sequence>
        );
      })}

      {/* outro — last 2s */}
      <Sequence from={(90 - 2) * FPS} durationInFrames={2 * FPS}>
        <Audio src={staticFile("vo/99-outro.mp3")} volume={1} />
      </Sequence>
    </>
  );
};
