import { factoryTodayString } from './working-hours.js';

export function fmtHmsForLog(sec) {
  if (!sec || sec < 1) return '0s';
  const h = Math.floor(sec / 3600);
  const m = Math.floor((sec % 3600) / 60);
  const s = sec % 60;
  if (h > 0) return `${h}h ${m}m ${s}s`;
  if (m > 0) return `${m}m ${s}s`;
  return `${s}s`;
}

/** Cron — End of Day summary (console + optional R2) */
export async function sendEODSummary(env) {
  const today = factoryTodayString(env);
  const stats = await env.DB.prepare(
    `SELECT stat_date, total_units, total_sec,
        tailor_01_units, tailor_02_units, hand_work_units, stone_work_units,
        button_units, embroidery_units, ari_work_units, hand_designing_units,
        invoice_maker_units, packaging_units, checker_units
     FROM daily_stats WHERE stat_date = ?`
  )
    .bind(today)
    .first();

  const sessions = await env.DB.prepare(
    `SELECT MAX(emp_name) as emp_name, MAX(emp_process) as emp_process, COUNT(*) as units
     FROM sessions WHERE day_date = ? GROUP BY emp_id ORDER BY units DESC LIMIT 5`
  )
    .bind(today)
    .all();

  const avgSec = stats && stats.total_units > 0 ? Math.round(stats.total_sec / stats.total_units) : 0;

  let msg = '\uD83D\uDCCA *AbaYa Track — End of Day Report*\n';
  msg += `_${today}_\n\n`;
  msg += '\uD83D\uDC54 *Production Summary*\n';
  msg += `\u2022 Total Completed: *${stats ? stats.total_units : 0} units*\n`;
  msg += `\u2022 Avg Cycle Time: *${fmtHmsForLog(avgSec)}*\n`;
  const u = stats || {};
  msg +=
    `\u2022 Tailor (01): ${u.tailor_01_units || 0} | Tailor (02): ${u.tailor_02_units || 0}` +
    ` | Hand Work: ${u.hand_work_units || 0}\n`;
  msg +=
    `\u2022 Stone Work: ${u.stone_work_units || 0} | Button: ${u.button_units || 0}` +
    ` | Embroidery: ${u.embroidery_units || 0}\n`;
  msg +=
    `\u2022 Ari Work: ${u.ari_work_units || 0} | Hand Designing: ${u.hand_designing_units || 0}\n`;
  msg +=
    `\u2022 Invoice maker: ${u.invoice_maker_units || 0} | Packaging: ${u.packaging_units || 0}` +
    ` | Checker: ${u.checker_units || 0}\n\n`;
  msg += '\uD83C\uDFC6 *Top Performers Today*\n';
  (sessions.results || []).forEach((r, i) => {
    msg += `${i + 1}. ${r.emp_name} \u2014 ${r.units} units (${r.emp_process})\n`;
  });
  msg += '\n\u2705 _Auto-generated by AbaYa Track Server_';

  if (env.EXPORTS) {
    await env.EXPORTS.put(`eod/${today}.txt`, msg, {
      httpMetadata: { contentType: 'text/plain' },
    });
  }

  console.log('EOD Summary generated for', today, ':', stats);
}
